version: "3.0"

services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "rsd-db"
      POSTGRES_USER: "rsd"
      POSTGRES_PASSWORD: "securepassword"

  backend:
    build: ./backend-postgrest
    ports:
      - "3500:3000"
    environment:
      PGRST_DB_URI: "postgres://authenticator:simplepassword@database:5432/rsd-db"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_DB_SCHEMA: "public"

  data-migration:
    build: ./data-migration
    depends_on:
      - "database"
      - "backend"
    network_mode: "host"
